Api user groups
techclubjacobs/server pull request #2
Opened 2019-04-03 13:01 UTC by taiyrbegeyev

Implement all endpoints for User Groups. Authentication is needed to restrict **PUT** and **DELETE** methods

2019-04-04 15:01 UTC, mgranderath requested changes
Lots of comments but otherwise good work! :tada:

2019-04-04 15:01 UTC, mgranderath commented on src/routes/usergroups.ts
> +                VALUES('${title}', '${max_capacity}', '${descrip}')`;
This permits SQL injection. Please read up on it and change this

2019-04-04 15:01 UTC, mgranderath commented on src/routes/usergroups.ts
> +            let sql = `SELECT * FROM UserGroup WHERE usergroup_id = '${ugid}'`;
Same as above

2019-04-04 15:01 UTC, mgranderath commented on src/routes/usergroups.ts
> +                WHERE usergroup_id = '${ugid}' `;
Again :)

2019-04-04 15:01 UTC, mgranderath commented on src/routes/usergroups.ts
> +            db.connection.query(sql, (error, results, fields) => {
Again

2019-04-04 15:01 UTC, mgranderath commented on src/routes/usergroups.ts
> +                WHERE usergroup_id = '${ugid}'`;
Again and a couple of other times below

2019-04-04 15:01 UTC, mgranderath commented on src/routes/usergroups.ts
> +        else {
It's more readable if you remove the `else` here since you return inside the `if` anyways.
```suggestion
            if () {
              return something;
            }
            ... rest of code
```

2019-04-04 15:01 UTC, mgranderath commented on src/routes/usergroups.ts
> +    app.get('/api/v1/usergroup', (req: any, res) => {
Don't use implicit `any` please. You should use this `(req: Request, res: Response)`

2019-04-06 07:47 UTC, taiyrbegeyev commented
Thank you, Malte. I fixed SQL injections and made the code more readable as you suggested

2019-04-07 06:50 UTC, mgranderath submitted a review, later dismissed
Already looks way better just one more comment :)

2019-04-07 06:50 UTC, mgranderath commented on src/routes/usergroups.ts
> +        let descrip = req.query.descrip;
I just saw all of these are query parameters but especially for POST, PUT this is a bad practice. In this case, you should get `title`, `descrip` and `max_capacity` from the JSON POST content instead

2019-04-13 19:50 UTC, taiyrbegeyev commented
Ready to be merged

2019-04-15 17:20 UTC, merged